name: ci

on:
  create:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest